### ISSUE TITLE
精錬ピッケルを利用することで、破壊を許可されていない人物が保護領域内のブロックを複製できる。

### ISSUE THREAD

**Issue by Noxious1772** [ryuuta0217/UnknownNetworkCore#48]
精錬ピッケルを利用し、保護されたブロックを掘ることで対象のブロックが増殖する。
増殖するためには、対象の保護領域で破壊を許可されていない人物が行う必要がある。
増殖に当たって、シュルカーボックスの中身などはそのまま保持される。

**Comment by ryuuta0217** [comment]
reference: https://github.com/elBukkit/worldguard/blob/master/src/main/java/com/sk89q/worldguard/bukkit/WorldGuardBlockListener.java
